void MakeDataSkims() {
  // Example of Root macro to copy a subset of a Tree to a new Tree
  // Only selected entries are copied to the new Tree.
  // The input file has been generated by the program in $ROOTSYS/test/Event
  // with   Event 1000 1 99 1
  //Author: Rene Brun
   
  //  gSystem->Load("$ROOTSYS/test/libEvent");

  //Get old file, old tree and set top branch address

  TChain oldtree("tree");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleElectron_Run2012A-13Jul2012-v1_AOD/merged_frbaby.root            ");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleElectron_Run2012A-recover-06Aug2012-v1_AOD/merged_frbaby.root	");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleElectron_Run2012B-13Jul2012-v1_AOD/merged_frbaby_1.root		");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleElectron_Run2012B-13Jul2012-v1_AOD/merged_frbaby.root		");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleElectron_Run2012C-24Aug2012-v1_AOD/merged_frbaby.root		");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleElectron_Run2012C-PromptReco-v2_AOD/merged_frbaby_1.root		");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleElectron_Run2012C-PromptReco-v2_AOD/merged_frbaby.root		");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleElectron_Run2012D-PromptReco-v1_AOD/merged_frbaby_1.root		");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleElectron_Run2012D-PromptReco-v1_AOD/merged_frbaby.root		");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleMu_Run2012A-13Jul2012-v1_AOD/merged_frbaby.root			");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleMu_Run2012A-recover-06Aug2012-v1_AOD/merged_frbaby.root		");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleMu_Run2012B-13Jul2012-v4_AOD/merged_frbaby_1.root		");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleMu_Run2012B-13Jul2012-v4_AOD/merged_frbaby.root			");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleMu_Run2012C-24Aug2012-v1_AOD/merged_frbaby.root			");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleMu_Run2012C-PromptReco-v2_AOD/merged_frbaby_1.root		");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleMu_Run2012C-PromptReco-v2_AOD/merged_frbaby_2.root		");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleMu_Run2012C-PromptReco-v2_AOD/merged_frbaby.root			");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleMu_Run2012D-PromptReco-v1_AOD/merged_frbaby_1.root		");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleMu_Run2012D-PromptReco-v1_AOD/merged_frbaby_2.root		");
//  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleMu_Run2012D-PromptReco-v1_AOD/merged_frbaby.root			");
  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/SingleMu_Run2012A-13Jul2012-v1_AOD/merged_frbaby.root");
  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/SingleMu_Run2012A-recover-06Aug2012-v1_AOD/merged_frbaby.root");
  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/SingleMu_Run2012B-13Jul2012-v1_AOD/merged_frbaby_1.root");
  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/SingleMu_Run2012B-13Jul2012-v1_AOD/merged_frbaby_2.root");
  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/SingleMu_Run2012B-13Jul2012-v1_AOD/merged_frbaby_3.root");
  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/SingleMu_Run2012B-13Jul2012-v1_AOD/merged_frbaby.root");
  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/SingleMu_Run2012C-24Aug2012-v1_AOD/merged_frbaby.root");
  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/SingleMu_Run2012C-PromptReco-v2_AOD/merged_frbaby_1.root");
  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/SingleMu_Run2012C-PromptReco-v2_AOD/merged_frbaby_2.root");
  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/SingleMu_Run2012C-PromptReco-v2_AOD/merged_frbaby_3.root");
  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/SingleMu_Run2012C-PromptReco-v2_AOD/merged_frbaby_4.root");
  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/SingleMu_Run2012C-PromptReco-v2_AOD/merged_frbaby.root");
  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/SingleMu_Run2012D-PromptReco-v1_AOD/merged_frbaby_1.root");
  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/SingleMu_Run2012D-PromptReco-v1_AOD/merged_frbaby_2.root");
  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/SingleMu_Run2012D-PromptReco-v1_AOD/merged_frbaby_3.root");
  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/SingleMu_Run2012D-PromptReco-v1_AOD/merged_frbaby_4.root");
  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/SingleMu_Run2012D-PromptReco-v1_AOD/merged_frbaby_5.root");
  oldtree.Add("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/SingleMu_Run2012D-PromptReco-v1_AOD/merged_frbaby.root");

  //  TFile *oldfile = new TFile("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleMu_Run2012C-PromptReco-v2_AOD/merged_frbaby_2.root");
  //  TTree *oldtree = (TTree*)oldfile->Get("tree");
  Long64_t nentries = oldtree.GetEntries();
//  Event *event   = 0;
//  oldtree->SetBranchAddress("event",&event);
  int mu8, mu17, mu24 = 0;
  oldtree.SetBranchAddress("mu8_vstar", &mu8);
  oldtree.SetBranchAddress("mu17_vstar", &mu17);
  oldtree.SetBranchAddress("mu24_eta2p1_vstar", &mu24);


  //Create a new file + a clone of old tree in new file
  TFile *newfile = new TFile("SingleMuonSmallFRbaby.root","recreate");
  TTree *newtree = oldtree.CloneTree(0);

  for (Long64_t i=0;i<nentries; i++) {
  //  for (Long64_t i=0;i<100000; i++) {
    oldtree.GetEntry(i);
    if (mu8 > 1 || mu17 > 1 || mu24 > 1) newtree->Fill();
    mu8=0;
    mu17=0;
    mu24=0;

    if (i%10000 == 0) cout<<i<<" out of "<<nentries<<endl;
  }
  newtree->Print();
  newtree->AutoSave();
  delete oldfile;
  delete newfile;
}
