void MakeFRSynchTree() {
  // Example of Root macro to copy a subset of a Tree to a new Tree
  // Only selected entries are copied to the new Tree.
  // The input file has been generated by the program in $ROOTSYS/test/Event
  // with   Event 1000 1 99 1
  //Author: Rene Brun
   
  //  gSystem->Load("$ROOTSYS/test/libEvent");

  //Get old file, old tree and set top branch address

  TChain oldtree("tree");
  oldtree.Add("/home/users/gzevi/FakeLepton/pac/analysis/FakeRateBabyMaker/SynchMuNtuple1.root");
  oldtree.Add("/home/users/gzevi/FakeLepton/pac/analysis/FakeRateBabyMaker/SynchMuNtuple2.root");

  //  TFile *oldfile = new TFile("/nfs-7/userdata/fgolf/babies/fr/FakeRate14May2013/DoubleMu_Run2012C-PromptReco-v2_AOD/merged_frbaby_2.root");
  //  TTree *oldtree = (TTree*)oldfile->Get("tree");
  Long64_t nentries = oldtree.GetEntries();
//  Event *event   = 0;
//  oldtree->SetBranchAddress("event",&event);
  UInt_t evt = 0;
  int id, run, lumi, chamber_hits, matched_stations, pixel_hits, nlayers = -1;
  bool is_global, is_pf, passed_id, is_loose, is_tight = false;
  float pt, eta, phi, chi2, ndof, d0, dz, chiso, nhiso, emiso, dbeta, iso = -999.;
  oldtree.SetBranchAddress("id", &id);
  oldtree.SetBranchAddress("run",&run);
  oldtree.SetBranchAddress("ls",&lumi );
  oldtree.SetBranchAddress("evt",&evt );
  oldtree.SetBranchAddress("pt",&pt );
  oldtree.SetBranchAddress("eta",&eta );
  oldtree.SetBranchAddress("phi",&phi );
  oldtree.SetBranchAddress("mu_numberOfValidMuonHits",&chamber_hits );
  oldtree.SetBranchAddress("mu_numberOfMatchedStations",&matched_stations );
  oldtree.SetBranchAddress("mu_numberOfValidPixelHits",&pixel_hits );
  oldtree.SetBranchAddress("mu_trackerLayersWithMeasurement",&nlayers );
  oldtree.SetBranchAddress("mu_nchi2global",&chi2 ); // should be chi2, not nchi2!!
  // missing ndof
  oldtree.SetBranchAddress("d0",&d0 );
  oldtree.SetBranchAddress("dz",&dz );
  oldtree.SetBranchAddress("ch_pfiso03",&chiso );
  oldtree.SetBranchAddress("nh_pfiso03",&nhiso );
  oldtree.SetBranchAddress("em_pfiso03",&emiso );
  oldtree.SetBranchAddress("cpfiso03_db",&dbeta );
  oldtree.SetBranchAddress("mu_isGlobal",&is_global );
  oldtree.SetBranchAddress("mu_isPF",&is_pf );
  

  // Need to add Iso, is_global, is_pf
  UInt_t ulumi, urun, uchamber_hits, umatched_stations, upixel_hits, unlayers = 0;
  float iso = 0;
  //Create a new file + a clone of old tree in new file
  TFile *newfile = new TFile("synchTree.root","recreate");
  TTree *newtree = new TTree("tree", "tree");
  newtree->Branch("run", &urun);
  newtree->Branch("lumi", &ulumi);
  newtree->Branch("evt", &evt);
  newtree->Branch("pt",&pt );
  newtree->Branch("eta",&eta );
  newtree->Branch("phi",&phi );
  newtree->Branch("chamber_hits", &uchamber_hits);
  newtree->Branch("matched_stations", &umatched_stations);
  newtree->Branch("pixel_hits", &upixel_hits);
  newtree->Branch("nlayers", &unlayers);
  newtree->Branch("d0", &d0);
  newtree->Branch("dz", &dz);
  newtree->Branch("chiso", &chiso);
  newtree->Branch("nhiso", &nhiso);
  newtree->Branch("emiso", &emiso);
  newtree->Branch("dbeta", &dbeta);
  newtree->Branch("iso", &iso);
  newtree->Branch("is_global", &is_global);
  newtree->Branch("is_pf", &is_pf);
  newtree->Branch("passed_id", &passed_id);
  newtree->Branch("is_loose", &is_loose);
  newtree->Branch("is_tight", &is_tight);


  bool passChi2, passMuHits, passStations, passLayers, passPixel, passD0_l, passD0_t, passDZ, passIso_l, passIso_t = false;
  //  for (Long64_t i=0;i<1000; i++) {
  for (Long64_t i=0;i<nentries; i++) {

    oldtree.GetEntry(i);
    if (abs(id)!=13) continue;
    ulumi=(UInt_t)lumi;
    urun=(UInt_t)run;
    if (chamber_hits >= 0)  uchamber_hits=(UInt_t)chamber_hits;
    if (matched_stations >= 0)  umatched_stations=(UInt_t)matched_stations;
    if (pixel_hits >= 0)  upixel_hits=(UInt_t)pixel_hits;
    if (nlayers >= 0)  unlayers=(UInt_t)nlayers;
    iso=(chiso + max(0.0, nhiso + emiso - 0.5 * dbeta))/pt;
    // Muon ID
    passChi2 = (chi2 < 10);
    passMuHits = (chamber_hits > 0);
    passStations = (matched_stations > 1);
    passLayers = (nlayers > 5);
    passPixel = (pixel_hits > 0);
    passD0_l = (fabs(d0) < 0.2);
    passD0_t = (fabs(d0) < 0.01);
    passDZ = (fabs(dz) < 0.2);
    passIso_l = (iso < 1.);
    passIso_t = (iso < 0.1);
    passed_id = is_global && is_pf && passChi2 && passMuHits && passStations && passLayers && passPixel && passDZ;
    is_loose = passed_id && passD0_l && passIso_l;
    is_tight = passed_id && passD0_t && passIso_t;
    newtree->Fill();

    //    if (i%10000 == 0) cout<<i<<" out of "<<nentries<<endl;
  }
  newtree->Print();
  newtree->AutoSave();
  delete newfile;
}
